version: '3.8'
services:
  whatsapp:
    build: .
    container_name: whatsapp-service
    volumes:
      - ./session:/app/session  # Persistir la carpeta de sesión
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
